Chore: e2e tests on slider component (Issue/201)
adaptlearning/adapt-contrib-slider pull request #202
Opened 2024-03-26 19:43 UTC by lemmyadams

Addresses #201

2024-03-27 11:01 UTC, lemmyadams commented
Relies on https://github.com/adaptlearning/adapt_framework/pull/3533

2024-03-28 09:49 UTC, cahirodoherty-learningpool approved these changes
👀

2024-03-28 12:23 UTC, ethan-lp approved these changes

2024-04-08 11:53 UTC, oliverfoster requested changes

2024-04-08 11:53 UTC, oliverfoster commented on test/e2e/slider.cy.js
> +      cy.testContainsOrNotExists('.slider__instruction', sliderComponent.instruction)
```suggestion
    const sliderComponents = this.data.components.filter(component => component._component === 'slider')
    sliderComponents.forEach(sliderComponent => {
      cy.visit(`/#/preview/${sliderComponent._id}`);
      const stripHtml= cy.helpers.stripHtmlstripHtml;
      cy.testContainsOrNotExists('.slider__body', stripHtml(bodyWithoutHtml));
      cy.testContainsOrNotExists('.slider__title', stripHtml(sliderComponent.displayTitle));
      cy.testContainsOrNotExists('.slider__instruction', stripHtml(sliderComponent.instruction));
```

Please use the line ending `;` appropriately.

2024-04-11 13:39 UTC, oliverfoster approved these changes

2024-04-11 13:39 UTC, merged